// Image pipeline. Four sources with different rules:
//
//   pexels    — licensed stock (Pexels license: free commercial use, no
//               attribution required). Allowed in previews AND live sites.
//               Needs PEXELS_API_KEY.
//   openverse — CC0/public-domain stock via the Openverse API. No key
//               needed, so stock photos work out of the box; restricted to
//               license=cc0 so live use needs no attribution (we keep the
//               creator credit anyway). Allowed in previews AND live sites.
//   places    — the business's real storefront photo from Google Places.
//               PREVIEW ONLY: Places photos are user-contributed and Google's
//               terms restrict reuse outside Places-powered apps, so they are
//               stripped from every deploy pack and publish automatically.
//   client    — photos the owner supplies at onboarding. The live-site source
//               of truth.
//   ai        — bespoke photography generated with the keyless Pollinations
//               Flux API from per-industry prompts (interiors and detail
//               shots only, never people — AI faces are the tell). No
//               third-party rights attach, so AI photos are allowed live;
//               the stored credit says plainly that the image is generated.
//
// Sources with reuse terms we can't verify (Pinterest boards, Google Images,
// social scrapes) are deliberately NOT sources: pins are third-party
// copyrighted photos with no reuse license, and a paid client site is the
// worst possible place to ship one.
//
// Bytes are cached under data/images/<leadId>/. Sites embed images as data
// URIs in preview mode and as relative files in live mode — either way the
// site makes zero external requests, and an <img> only renders when its
// bytes exist on disk (impeccable's broken-image rule).
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { DATA_DIR } from './store.js';

const IMAGES_DIR = path.join(DATA_DIR, 'images');
const MAX_IMAGE_BYTES = 8 * 1024 * 1024;
const ALLOWED_TYPES = { 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp' };
// The committed per-industry photo library (assets/demo-photos/<key>_{hero,detail}.jpg),
// generated by the Pollinations workflow. Used as an instant, offline, keyless
// default so a generated site is never empty.
const BUNDLED_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'assets', 'demo-photos');

export function imageProviders() {
  return {
    pexels: Boolean(process.env.PEXELS_API_KEY),
    openverse: true, // keyless — the Openverse API needs no credentials
    ai: true,        // keyless — Pollinations needs no credentials
    places: Boolean(process.env.GOOGLE_PLACES_API_KEY),
  };
}

// Curated per-industry queries — "bakery bread oven warm light" finds a
// usable photo; "bakery" finds birthday clip art.
const STOCK_QUERIES = {
  restaurant: ['restaurant interior candlelight table', 'chef plating dish kitchen', 'pasta dish rustic table'],
  cafe: ['coffee shop counter espresso machine', 'latte art wooden table', 'cafe interior morning light'],
  bakery: ['artisan bread sourdough crust', 'bakery pastry display case', 'baker hands kneading dough'],
  salon: ['hair salon stylist working', 'salon interior chairs mirrors', 'barber cutting hair close up'],
  trades: ['plumber working pipes tools', 'electrician panel work', 'contractor tool belt work site'],
  auto: ['mechanic under car garage', 'auto repair shop lift', 'engine repair hands tools'],
  health: ['modern clinic reception calm', 'dentist office chair clean', 'medical professional patient care'],
  fitness: ['gym barbell chalk training', 'fitness class group workout', 'weights rack gym interior'],
  professional: ['modern office meeting handshake', 'desk documents pen professional', 'office interior natural light'],
  retail: ['boutique shop interior shelves', 'shopkeeper small business counter', 'store display products warm'],
  hospitality: ['cozy hotel room bed linen', 'bed and breakfast exterior morning', 'hotel lobby warm welcome'],
  generic: ['small business storefront street', 'local shop owner counter', 'main street small town shops'],
};

function leadImageDir(leadId) {
  const dir = path.join(IMAGES_DIR, leadId.replace(/[^\w-]/g, ''));
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

async function fetchBytes(url, headers = {}, timeoutMs = 20000) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, { headers, redirect: 'follow', signal: controller.signal });
    if (!res.ok) throw new Error(`HTTP ${res.status} fetching image`);
    const type = res.headers.get('content-type')?.split(';')[0] || '';
    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.length > MAX_IMAGE_BYTES) throw new Error('Image too large');
    return { buf, type };
  } finally {
    clearTimeout(timer);
  }
}

function saveImage(leadId, source, buf, type, meta = {}) {
  const ext = ALLOWED_TYPES[type] || 'jpg';
  const id = 'img_' + crypto.randomBytes(5).toString('hex');
  const file = path.join(leadImageDir(leadId), `${id}.${ext}`);
  fs.writeFileSync(file, buf);
  return {
    id,
    source,
    file: path.relative(DATA_DIR, file),
    type: type || 'image/jpeg',
    bytes: buf.length,
    previewOnly: source === 'places',
    addedAt: new Date().toISOString(),
    ...meta,
  };
}

export function readImageBytes(image) {
  try {
    const full = path.join(DATA_DIR, image.file);
    if (!full.startsWith(IMAGES_DIR)) return null;
    return fs.readFileSync(full);
  } catch {
    return null;
  }
}

export function imageDataUri(image) {
  const buf = readImageBytes(image);
  return buf ? `data:${image.type};base64,${buf.toString('base64')}` : null;
}

export function deleteImage(lead, imageId) {
  const image = (lead.images || []).find((i) => i.id === imageId);
  if (!image) return false;
  try { fs.unlinkSync(path.join(DATA_DIR, image.file)); } catch { /* already gone */ }
  return true;
}

// ---- Stock photos: Pexels (key) with Openverse CC0 (keyless) fallback ----

async function pexelsCandidates(industry, perQuery) {
  const key = process.env.PEXELS_API_KEY;
  const queries = STOCK_QUERIES[industry] || STOCK_QUERIES.generic;
  const candidates = [];
  for (const query of queries.slice(0, 2)) {
    const url = `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=${perQuery}&orientation=landscape`;
    const res = await fetch(url, { headers: { Authorization: key } });
    if (!res.ok) throw new Error(`Pexels error (HTTP ${res.status})`);
    const data = await res.json();
    for (const photo of data.photos || []) {
      candidates.push({
        candidateId: `pexels_${photo.id}`,
        provider: 'pexels',
        license: 'Pexels license',
        thumb: photo.src.medium,          // shown in the dashboard picker only
        full: photo.src.large2x || photo.src.large,
        photographer: photo.photographer,
        query,
      });
    }
  }
  return candidates;
}

// license=cc0 only: public-domain dedication, so a paid client site can use
// the photo with no attribution obligation (we keep the creator credit
// anyway). Unauthenticated Openverse allows a modest rate — fine for a
// picker; register a key with them if you ever need volume.
async function openverseCandidates(industry, perQuery) {
  const queries = STOCK_QUERIES[industry] || STOCK_QUERIES.generic;
  const candidates = [];
  for (const query of queries.slice(0, 2)) {
    const url = `https://api.openverse.org/v1/images/?q=${encodeURIComponent(query)}&license=cc0&aspect_ratio=wide&per_page=${perQuery}`;
    const res = await fetch(url, { headers: { 'User-Agent': 'SiteSpark/1.0' } });
    if (!res.ok) throw new Error(`Openverse error (HTTP ${res.status})`);
    const data = await res.json();
    for (const img of data.results || []) {
      if (!img.url) continue;
      candidates.push({
        candidateId: `openverse_${img.id}`,
        provider: 'openverse',
        license: 'CC0 (public domain)',
        thumb: img.thumbnail || img.url,
        full: img.url,
        photographer: img.creator || null,
        query,
      });
    }
  }
  return candidates;
}

export async function stockCandidates(lead, industry, { perQuery = 3 } = {}) {
  if (process.env.PEXELS_API_KEY) {
    try {
      const picks = await pexelsCandidates(industry, perQuery);
      if (picks.length) return picks;
    } catch (err) {
      console.error('[images] Pexels failed, falling back to Openverse:', err.message);
    }
  }
  return openverseCandidates(industry, perQuery);
}

export async function attachStockImage(lead, candidate) {
  const { buf, type } = await fetchBytes(candidate.full);
  // Openverse URLs don't guarantee a content-type up front — reject anything
  // that isn't a real photo format before it can reach a page.
  if (!ALLOWED_TYPES[type]) throw new Error(`Unsupported image type ${type || '(none)'} from source.`);
  const source = candidate.provider || 'pexels';
  const credit = source === 'openverse'
    ? (candidate.photographer ? `Photo: ${candidate.photographer} (CC0, via Openverse)` : 'Public-domain photo via Openverse')
    : (candidate.photographer ? `Photo: ${candidate.photographer} / Pexels` : 'Photo: Pexels');
  return saveImage(lead.id, source, buf, type, {
    alt: `${candidate.query} at ${lead.name}`.replace(/\s+/g, ' '),
    credit,
  });
}

// ---- Google Places (storefront, preview only) ----

export async function fetchStorefront(lead) {
  const key = process.env.GOOGLE_PLACES_API_KEY;
  if (!key) throw new Error('Set GOOGLE_PLACES_API_KEY to pull the storefront photo from Google Maps.');
  if (lead.source === 'demo') throw new Error('Demo leads are fictional; no real storefront exists.');

  const input = encodeURIComponent(`${lead.name} ${lead.address || lead.city || ''}`.trim());
  const findUrl = `https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input=${input}&inputtype=textquery&fields=place_id,photos,name&key=${key}`;
  const found = await (await fetch(findUrl)).json();
  const photoRef = found?.candidates?.[0]?.photos?.[0]?.photo_reference;
  if (!photoRef) throw new Error('No photo found on the Google listing for this business.');

  const photoUrl = `https://maps.googleapis.com/maps/api/place/photo?maxwidth=1400&photo_reference=${photoRef}&key=${key}`;
  const { buf, type } = await fetchBytes(photoUrl);
  return saveImage(lead.id, 'places', buf, type, {
    alt: `${lead.name} storefront`,
    credit: 'Photo from the business’s Google listing (preview only)',
  });
}

// ---- AI-generated photography (Pollinations Flux, keyless) ----

// Interiors, storefronts, and detail shots only — no people (generated faces
// are the instant AI tell) and no text (Flux mangles signage). A shared
// style suffix keeps the set looking like one photographer shot it.
const AI_STYLE = 'editorial photography, warm natural light, shallow depth of field, no people, no faces, no text, no watermark';
export const AI_PROMPTS = {
  restaurant: [
    { prompt: `intimate neighborhood restaurant interior at dusk, candlelit tables, ${AI_STYLE}`, alt: 'Candlelit restaurant interior' },
    { prompt: `rustic plated pasta dish on a wooden table beside a glass of red wine, ${AI_STYLE}`, alt: 'Plated pasta dish on a wooden table' },
  ],
  cafe: [
    { prompt: `sunlit independent coffee shop counter with espresso machine and pastry case, ${AI_STYLE}`, alt: 'Sunlit coffee shop counter' },
    { prompt: `latte with leaf art on a small marble table by a window, ${AI_STYLE}`, alt: 'Latte on a marble table by a window' },
  ],
  bakery: [
    { prompt: `artisan bakery interior with wooden shelves of fresh sourdough loaves, ${AI_STYLE}`, alt: 'Bakery shelves with fresh sourdough loaves' },
    { prompt: `close-up of a scored sourdough boule with flour dusting on a cooling rack, ${AI_STYLE}`, alt: 'Scored sourdough loaf on a cooling rack' },
  ],
  salon: [
    { prompt: `calm boutique hair salon interior, styling chair before a large round mirror, plants and warm wood, ${AI_STYLE}`, alt: 'Boutique salon styling chair and mirror' },
    { prompt: `close-up of professional salon shears and combs arranged on a linen cloth, ${AI_STYLE}`, alt: 'Salon shears and combs on a linen cloth' },
  ],
  trades: [
    { prompt: `neatly organized tradesman workshop wall of hand tools and copper pipe fittings, ${AI_STYLE}`, alt: 'Organized workshop wall of tools and fittings' },
    { prompt: `close-up of polished copper pipework and brass valves on a workbench, ${AI_STYLE}`, alt: 'Copper pipework and brass valves on a workbench' },
  ],
  auto: [
    { prompt: `clean independent auto repair garage interior with a car on a lift, ${AI_STYLE}`, alt: 'Auto repair garage with a car on a lift' },
    { prompt: `close-up of chrome socket wrench set arranged in a rolling tool chest drawer, ${AI_STYLE}`, alt: 'Socket wrench set in a tool chest' },
  ],
  health: [
    { prompt: `calm modern clinic reception with soft seating and plants, ${AI_STYLE}`, alt: 'Calm clinic reception with soft seating' },
    { prompt: `minimal treatment room with neatly made exam chair and natural light, ${AI_STYLE}`, alt: 'Bright, tidy treatment room' },
  ],
  fitness: [
    { prompt: `independent gym interior with kettlebell rack and rings in morning light, ${AI_STYLE}`, alt: 'Gym interior with kettlebells and rings' },
    { prompt: `close-up of chalked barbell knurling on a lifting platform, ${AI_STYLE}`, alt: 'Chalked barbell on a lifting platform' },
  ],
  professional: [
    { prompt: `calm small office meeting room, wooden table, notebooks and glass water carafe, ${AI_STYLE}`, alt: 'Small office meeting room' },
    { prompt: `close-up of a fountain pen resting on printed documents, ${AI_STYLE}`, alt: 'Fountain pen on printed documents' },
  ],
  retail: [
    { prompt: `charming small boutique interior with wooden shelves of curated goods, ${AI_STYLE}`, alt: 'Boutique interior with curated shelves' },
    { prompt: `close-up of kraft-paper wrapped parcels tied with twine on a shop counter, ${AI_STYLE}`, alt: 'Wrapped parcels on a shop counter' },
  ],
  hospitality: [
    { prompt: `cozy guesthouse bedroom with crisp white linen and morning light through curtains, ${AI_STYLE}`, alt: 'Cozy guesthouse bedroom in morning light' },
    { prompt: `breakfast tray with croissants and coffee on a windowsill, ${AI_STYLE}`, alt: 'Breakfast tray on a windowsill' },
  ],
  generic: [
    { prompt: `charming small-town storefront with awning and flower boxes at golden hour, ${AI_STYLE}`, alt: 'Small-town storefront at golden hour' },
    { prompt: `close-up of an open sign hanging in a shop door window, glass reflections, ${AI_STYLE}`, alt: 'Open sign in a shop door window' },
  ],
};

function aiImageUrl(prompt, { width = 1216, height = 832, seed = 7 } = {}) {
  return `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=${width}&height=${height}&model=flux&nologo=true&seed=${seed}`;
}

// Attach pre-generated AI bytes (used by generateAiImages below and by
// anything that produced the image elsewhere, e.g. the GitHub Actions
// generation workflow used when a network policy blocks the API locally).
export function attachAiBytes(lead, buf, type, { alt }) {
  if (!ALLOWED_TYPES[type]) throw new Error(`Unsupported image type ${type || '(none)'} — expected JPEG, PNG, or WebP.`);
  if (!buf?.length) throw new Error('Empty image.');
  if (buf.length > MAX_IMAGE_BYTES) throw new Error('Image too large (8MB max).');
  return saveImage(lead.id, 'ai', buf, type, {
    alt: alt || 'Generated photograph',
    credit: 'AI-generated photograph (Pollinations Flux)',
  });
}

export async function generateAiImages(lead, industry, { count = 2 } = {}) {
  const prompts = (AI_PROMPTS[industry] || AI_PROMPTS.generic).slice(0, count);
  // Seed from the lead id so a re-run regenerates the same set.
  let seed = [...String(lead.id)].reduce((a, c) => (a * 31 + c.charCodeAt(0)) % 99991, 7);
  const images = [];
  for (const { prompt, alt } of prompts) {
    const { buf, type } = await fetchBytes(aiImageUrl(prompt, { seed: ++seed }), {}, 90000);
    images.push(attachAiBytes(lead, buf, type, { alt }));
  }
  return images;
}

// Attach the built-in industry photo set (hero + detail) from the committed
// library so a generated site is never empty — instant, offline, no key, no
// network. These are AI-generated stock interiors, not the real business, so
// they're a live-legal preview the client swaps for their own photos; same
// honest 'ai' credit. Returns [] if the library isn't present.
export function bundledImagesAvailable() {
  try { return fs.readdirSync(BUNDLED_DIR).some((f) => f.endsWith('.jpg')); } catch { return false; }
}

export function attachBundledImages(lead, industry) {
  const key = fs.existsSync(path.join(BUNDLED_DIR, `${industry}_hero.jpg`)) ? industry : 'generic';
  const prompts = AI_PROMPTS[key] || AI_PROMPTS.generic;
  const specs = [
    [`${key}_hero.jpg`, prompts[0]?.alt || `${lead.name} interior`],
    [`${key}_detail.jpg`, prompts[1]?.alt || `${lead.name} detail`],
  ];
  const out = [];
  for (const [file, alt] of specs) {
    try {
      const buf = fs.readFileSync(path.join(BUNDLED_DIR, file));
      out.push(saveImage(lead.id, 'ai', buf, 'image/jpeg', {
        alt,
        credit: 'AI-generated photograph',
        bundled: true,
      }));
    } catch { /* file missing — skip, never block generation */ }
  }
  return out;
}

// ---- Client uploads (the live-site source) ----

export function attachClientImage(lead, { filename, contentType, dataBase64 }) {
  if (!ALLOWED_TYPES[contentType]) {
    throw new Error(`Unsupported image type ${contentType || '(none)'} — use JPEG, PNG, or WebP.`);
  }
  const buf = Buffer.from(String(dataBase64), 'base64');
  if (!buf.length) throw new Error('Empty image upload.');
  if (buf.length > MAX_IMAGE_BYTES) throw new Error('Image too large (8MB max). Resize and retry.');
  const cleanName = String(filename || 'photo').replace(/\.[a-z0-9]+$/i, '').slice(0, 60);
  return saveImage(lead.id, 'client', buf, contentType, {
    alt: `${cleanName} at ${lead.name}`.replace(/\s+/g, ' '),
  });
}

// ---- selection for rendering ----

// Preview shows the richest set (client first, then storefront, then stock).
// Live output must never include Places photos.
export function selectImages(lead, mode = 'preview') {
  const all = (lead.images || []).filter((i) => readImageBytes(i));
  const usable = mode === 'live' ? all.filter((i) => !i.previewOnly) : all;
  const bySource = (s) => usable.filter((i) => i.source === s);
  const ordered = [...bySource('client'), ...bySource('places'), ...bySource('pexels'), ...bySource('ai'), ...bySource('openverse')];
  return {
    hero: ordered[0] || null,                 // strongest photo leads
    gallery: ordered.slice(1, 4),
    excludedForLive: mode === 'live' ? all.filter((i) => i.previewOnly).length : 0,
  };
}
